### ISSUE TITLE
Crash with "invalid character" error message.

### ISSUE THREAD

**Issue by chrisjbillington** [steffenfritz/pacaudit#12]
**Describe the bug**
I've just installed the latest pacaudit from the AUR. When I run it, it is crashing with the error message `invalid character 'I' looking for beginning of value`

**To Reproduce**
1. run `pacaudit`

**Expected behavior**
List of vulnerable packages

**Actual behaviour**

bash

```
$ pacaudit -v
2020/02/21 16:21:17 invalid character 'I' looking for beginning of value
```

**Comment by chrisjbillington** [comment]
Oh, it's because https://security.archlnux.org is down.

The `I` in the error message is is from `Internal Server Error` :p 

Nonetheless, perhaps if pacaudit gets a non-200 response from security.archlinux.org it could crash with an error message saying that that's the issue

**Comment by steffenfritz** [comment]
Thanks for the report. Yes, valid point, this should be handled. I will take care of it.

**Comment by R-a-l-f** [comment]
Since we noticed the server issue during a thread at the Arch general mailing list, I first was against reporting the issue, but after rethinking it, I agree with you Chris. It should not result in an error message, but in a warning, mentioning that there is a server issue.

Thank you for reporting the issue, before I reconsidered my opinion.
