### ISSUE TITLE
Maybe missing vulnerablilities

### ISSUE THREAD

**Issue by Spacewalker2** [steffenfritz/pacaudit#18]
I did not really investigate this but it comes to my attention that the output of `pacaudit` misses some vulnerabilities which `arch-audit` is listing.

```
$ pacaudit
glibc-2.32-5
lua51-5.1.5-9
openssl-1.0-1.0.2.u-1
unzip-6.0-14
inetutils-1.9.4-8

5 vulnerable package(s) installed.
```

```
$ arch-audit
Package glibc is affected by CVE-2020-29562. Medium risk!
Package inetutils is affected by CVE-2019-0053. High risk!
Package linux is affected by CVE-2020-16119, CVE-2020-27815. High risk!
Package lua51 is affected by CVE-2014-5461. Medium risk!
Package openssl-1.0 is affected by CVE-2020-1968. Medium risk!
Package python-pip is affected by CVE-2018-20225. Low risk!
Package thunderbird is affected by CVE-2020-26970. High risk!
Package unzip is affected by CVE-2018-1000035. Low risk!
```

**Comment by steffenfritz** [comment]
Confirmed.
Prio: High

Root cause:
- pacaudit does not show packages if an update is available. 

Howto fix:
- Use https://security.archlinux.org/issues/all as data source

**Comment by steffenfritz** [comment]
There is also a bug in the comparison. 

As I have no time to fix this and pacaudit serves as a security tool not fixing this is not acceptable. The tool you mentioned, arch-audit, is in the community repo and has no known bugs.

pacaudit started because it had some features I was missing in arch-audit. However, the core functionality is the same.

I will therefore discontinue pacaudit and archive this repo. I will remove it also from the AUR.

Nevertheless, thanks for reporting!
